from flask import Flask, request, render_template_string
import os

app = Flask(__name__)

NOTES_FILE = "/data/notes.txt"

@app.route("/", methods=["GET", "POST"])
def home():
    if request.method == "POST":
        note = request.form.get("note", "")
        with open(NOTES_FILE, "a") as f:
            f.write(note + "\n")

    # Load existing notes
    if os.path.exists(NOTES_FILE):
        with open(NOTES_FILE, "r") as f:
            notes = f.read().splitlines()
    else:
        notes = []

    html = """
    <h1>Hello {{ username }}</h1>
    <form method="post">
        <input type="text" name="note" placeholder="Write your note">
        <input type="submit" value="Save">
    </form>
    <h2>Notes:</h2>
    <ul>{% for note in notes %}<li>{{ note }}</li>{% endfor %}</ul>
    """
    return render_template_string(html, username=os.environ.get("APP_USERNAME", "anonymous"), notes=notes)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)