apiVersion: v1
kind: Service
metadata:
  name: notepad-app
spec:
  type: LoadBalancer
  selector:
    app: notepad-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
